#!/bin/bash
awk -F $'\t' '{for(i=1; i<=(NF/2); i++) printf("%s%s", $i, \
					(i==NF/2)?"\n":"\t")}' $1 > $1.train.txt
awk -F $'\t' '{for(i=(NF/2)+1; i<=(NF); i++) printf("%s%s", $i, \
                                        (i==NF)?"\n":"\t")}' $1 > $1.test.txt

